import csv

intencoes = [
    {
        "tag": 'saudacao',
        "prioridade": 11,
        "palavras": "oi,ola,olá,bom dia,boa tarde,boa noite,tudo bem,como vai,eae,salve,fala,hey,hi,hello,oie,oii,oiii,ei,opa,oiiii,oiee,oieee,oiiiii,oiiiiii,oieeee,oiiiiiii,oioi,alô,alo,e aí,e ai,eai,e aew,aeew,oi sumido,olá tudo bem,olá tudo bom,boas,oi oi,oi tudo bem,olá olá,fala aí,fala ai,fala comigo,me fala,oi gente,olá pessoal,bom diaa,boa tardee,boa noitee,oi linda,oi lindo,oi meu bem,oi meu amor,oi bb,oi beba,oi bebê,psiu,psit,hey hey,yoo,yo,wassup,what's up,whats up,boa,boaa,boaaa,vim aqui,vim aqui te perguntar,posso perguntar,pode me ajudar,me ajuda,preciso de ajuda,socorro,oi preciso de ajuda",
        "resposta": 'Olá! Seja bem-vindo à FashionFlow 👋 Como posso te ajudar hoje?',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'exit',
        "prioridade": 1,
        "palavras": 'sair,encerrar,finalizar,tchau,até mais,falou,vlw,obrigado,obrigada,bye,goodbye,see you,xau,até logo,até breve,até a próxima,flw,valeu,thanks,obrigado pela ajuda,obrigada pela ajuda,tchauzinho,tchaau,xauzinho,até,atee,até logo logo,até mais mais,foi,foii,de nada,dispensado,dispensada,pode fechar,pode encerrar,encerrando,ok valeu,ok vlw,ok obrigado,ok obrigada,ok flw,ok falou,ok tchau,ok até,ok até mais,ok bye,ta bom obrigado,ta bom obrigada,ta bom vlw,ta bom falou,já era,jah era,até amanhã,até amanha,até semana que vem,tmj,tmjj,obg,obgg,mt obg,muito obrigado,muito obrigada,abraço,abraços,bjos,bjss,beijo,beijos,foi bom,foi ótimo,foi boa,foi boa a conversa',
        "resposta": 'Até mais! 👋 Retorne quando precisar.',
        "pergunta_seguinte": '',
        "encerrar": 'True',
    },
    {
        "tag": 'reembolso',
        "prioridade": 2,
        "palavras": 'reembolso,devolução,devolucao,estornar,estorno,reembolsos,devoluções,devolucoes,estornos,estornar pagamento,estornar compra,quero meu dinheiro de volta,dinheiro de volta,quero devolver,quero estornar,me reembolsa,me devolve o dinheiro,quando cai o reembolso,quando volta o dinheiro,quanto tempo o reembolso,prazo do estorno,prazo do reembolso,devolução do dinheiro,devolver o valor,estornar o valor,cancelar e reembolsar',
        "resposta": 'A devolução no Pix ocorre em até 24h pós-estorno. No cartão, em até 48h dependendo do banco.',
        "pergunta_seguinte": 'Deseja iniciar o processo de reembolso agora? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'pagamento_misto',
        "prioridade": 8,
        "palavras": 'misto,dois cartões,dois cartoes,dividir pagamento,pix e cartão,pagar com dois cartões,pagar com pix e cartão,pix e débito,pix e crédito,pagar com pix e débito,pagar com pix e crédito,dividir em dois cartões,dividir entre pix e cartão,dividir entre pix e débito,dividir entre pix e crédito,dividir entre dois cartões,dividir entre dois cartoes,pagar metade no pix e metade no cartão,pagar metade com pix e metade com cartão,pagar metade no pix e metade no débito,pagar metade com pix e metade com débito,pagar metade no pix e metade no crédito,pagar metade com pix e metade com crédito,pix e credito,pix e debito,pagar com pix e credito,pagar com pix e debito,dividir entre pix e credito,dividir entre pix e debito,pagar metade no pix,pagar metade com pix,dois meios de pagamento,mais de um cartão,mais de um cartao,pagar metade no cartão,pagar metade no cartao',
        "resposta": 'Atualmente, nosso sistema não suporta pagamento misto ou divisão em dois cartões.',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'forma_pagamento',
        "prioridade": 3,
        "palavras": 'formas de pagamento,formas de pagamentos,quais formas,como posso pagar,aceita o que,como pagar,quais formas de pagamento,quais formas de pagamentos,formas de pagamento aceitas,formas de pagamento disponíveis,quais formas de pagamento aceitas,quais formas de pagamento disponíveis,o que vocês aceitam,o que voces aceitam,o que aceita,quais são as formas,quais sao as formas,meios de pagamento,quais meios de pagamento,como faço pra pagar,como faco pra pagar,opções de pagamento,opcoes de pagamento,posso pagar de que forma,de que forma posso pagar',
        "resposta": 'Aceitamos:\n- Pix (5% de desconto)\n- Cartão de Crédito/Débito (Visa e Mastercard em até 12x sem juros) \n- Dinheiro (somente para retirada no local)',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'prazo_entrega',
        "prioridade": 4,
        "palavras": 'prazo,entrega,quando chega,frete,tempo de entrega,cep,calcular prazo,quando vai chegar,quando vai entregar,quanto tempo demora,quanto tempo leva,demora quanto,prazo de entrega,dias para entregar,dias úteis entrega,quando recebo,quando receberei,quando chega meu pedido,previsão de entrega,previsão entrega,estimativa de entrega,estimativa entrega,entrega rápida,entrega express,entrega expressa,entregar rápido,quero entrega rápida,tem entrega no dia,entrega hoje,entrega amanhã,entrega amanha',
        "resposta": 'O prazo de entrega varia conforme sua região e o tipo de frete escolhido.',
        "pergunta_seguinte": 'Deseja calcular o prazo exato informando seu CEP? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'desconto',
        "prioridade": 5,
        "palavras": 'cupom,desconto,voucher,promoção,promocao,descontos,cupons,promoçao,promoções,promocao ativa,promoção ativa,tem desconto,tem promoção,tem promocao,tem cupom,codigo de desconto,codigo desconto,cupom de desconto,como ganhar desconto,quero desconto,me da um desconto,me dá um desconto,tem alguma promoção,tem alguma promocao,tá em promoção,ta em promocao,está em promoção,esta em promocao,oferta,ofertas,liquidação,liquidacao,sale,black friday,desconto especial,preço especial,preco especial',
        "resposta": '🌟 Promoção ativa: 5% de desconto em compras via Pix! 🌟',
        "pergunta_seguinte": 'Deseja gerar a chave Pix agora? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'credito',
        "prioridade": 6,
        "palavras": 'crédito,credito,cartão de crédito,cartao de credito,pagar no crédito,pagar com crédito,pagar no credito,pagar com credito,cartão crédito,cartao credito,no crédito,no credito,com crédito,com credito,passar no crédito,passar no credito',
        "resposta": 'Pagamento no crédito disponível em até 12x sem juros.',
        "pergunta_seguinte": 'Qual a bandeira do cartão e quantidade de parcelas?\n(Ex: Visa, 3x)',
        "encerrar": '',
    },
    {
        "tag": 'parcela',
        "prioridade": 6,
        "palavras": 'parcelar,parcela,parcelas,vezes,pagar em parcelas,dividir pagamento,dividir em parcelas,pagar em vezes,pagar em parcela,pagar em vezes sem juros,parcelamento,quantidade de parcelas,dividir em vezes,dividir em parcela,dividir em vezes sem juros,quantas vezes,quantas parcelas,em quantas vezes,em quantas parcelas,tem parcelamento,posso parcelar,dá pra parcelar,da pra parcelar,como parcelar,como faço pra parcelar,juros,sem juros,com juros,tem juros,parcela sem juros,parcelamento sem juros,12x,12 vezes,12 parcelas',
        "resposta": 'Parcelamento disponível em até 12x sem juros no crédito.',
        "pergunta_seguinte": 'Qual a bandeira do cartão e quantidade de parcelas?\n(Ex: Visa, 3x)',
        "encerrar": '',
    },
    {
        "tag": 'debito',
        "prioridade": 6,
        "palavras": 'débito,debito,cartão de débito,cartao de debito,pagar no débito,pagar com débito,pagar no debito,pagar com debito,cartão débito,cartao debito,no débito,no debito,com débito,com debito,passar no débito,passar no debito',
        "resposta": 'Pagamento no débito disponível nas bandeiras Visa e Mastercard.',
        "pergunta_seguinte": 'Qual a bandeira do seu cartão de débito? (Ex: Visa)',
        "encerrar": '',
    },
    {
        "tag": 'bandeiras',
        "prioridade": 7,
        "palavras": 'bandeira,bandeiras,visa,master,mastercard,cartão,cartao,aceitam visa,aceitam mastercard,aceitam master,aceita visa,aceita mastercard,aceita master,qual bandeira,quais bandeiras,quais cartões aceitam,quais cartoes aceitam,que cartão aceita,que cartao aceita,elo,hipercard,amex,american express,aceita elo,aceita hipercard,aceita amex',
        "resposta": 'Aceitamos pagamentos via Visa e Mastercard! 💳✨',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'boleto',
        "prioridade": 8,
        "palavras": 'boleto,boleto bancario,pagar boleto,pagar com boleto,gerar boleto,tem boleto,aceita boleto,boleto bancário,quero pagar no boleto,posso pagar no boleto,pagar via boleto,pagamento via boleto,pagamento por boleto',
        "resposta": 'Infelizmente, não aceitamos boleto bancário.\nVocê pode pagar via Pix ou Cartão.',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'pix',
        "prioridade": 6,
        "palavras": 'pix,pagar no pix,pagamento pix,chave pix,pagar com pix,pix pago,fazer pix,transferência pix,transferencia pix,chave do pix,qual a chave pix,me passa a chave pix,me manda a chave pix,qr code pix,qr code,copia e cola pix,copia e cola,pagar via pix,pagamento via pix,pix instantâneo,pix instantaneo,aprovação pix,aprovacao pix,quanto tempo o pix,pix aprova na hora,pix é na hora,pix e na hora',
        "resposta": 'Temos pagamento via Pix com aprovação imediata e 5% de desconto!',
        "pergunta_seguinte": 'Deseja gerar a chave Pix para o pedido? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'dinheiro',
        "prioridade": 9,
        "palavras": 'dinheiro,especie,em espécie,pagar com dinheiro,pagar no dinheiro,pagar em dinheiro,dineiro,dindin,grana,pagar com dindin,pagar com grana,pagar com dineiro,pagar no dindin,pagar no grana,pagar no dineiro,pagar em dindin,pagar em grana,pagar em dineiro,pataco,em especie,dinheirinho,trocado,nota,notas,cédula,cedula,cash,pagar em cash,tem troco,troco,aceita dinheiro,aceita cash',
        "resposta": 'Aceitamos pagamento em dinheiro, porém somente para retirada no local. 🏬',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'nota_fiscal',
        "prioridade": 3,
        "palavras": 'nota fiscal,nf,nfe,nf-e,comprovante fiscal,nota da compra,fatura,nota eletronica,nota eletrônica,nota fiscal eletrônica,nota fiscal eletronica,nfce,nfc-e,preciso da nota,quero a nota fiscal,onde está minha nota,onde esta minha nota,não recebi nota fiscal,nao recebi nota fiscal,nota fiscal não chegou,nota fiscal nao chegou',
        "resposta": "A sua Nota Fiscal Eletrônica (NF-e) é enviada automaticamente para o e-mail cadastrado assim que o pagamento é faturado. Você também pode baixá-la na área 'Meus Pedidos' em nosso site.",
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'recusado_cartao_credito',
        "prioridade": 2,
        "palavras": 'crédito recusado,credito recusado,recusou crédito,recusou credito,erro no crédito,erro no credito,cartão de crédito não passou,cartao de credito nao passou,credito foi recusado,crédito foi recusado,crédito recusou,credito recusou,cartão recusado,cartao recusado,não aprovou o crédito,nao aprovou o credito,pagamento recusado crédito,pagamento recusado credito,deu erro no crédito,deu erro no credito,cartão não passou,cartao nao passou,não foi no crédito,nao foi no credito',
        "resposta": 'Ah, que pena! 😕 Cartões de crédito geralmente são recusados por falta de limite, digitação incorreta dos dados (como o CVV) ou bloqueio preventivo de segurança do seu banco.',
        "pergunta_seguinte": 'Você deseja conhecer as nossas formas de pagamento alternativas? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'recusado_cartao_debito',
        "prioridade": 2,
        "palavras": 'débito recusado,debito recusado,recusou débito,recusou debito,erro no débito,erro no debito,cartão de débito não passou,cartao de debito nao passou,debito foi recusado,débito foi recusado,débito recusou,debito recusou,não foi no débito,nao foi no debito,deu erro no débito,deu erro no debito,pagamento recusado débito,pagamento recusado debito',
        "resposta": 'Poxa, sinto muito! 😕 No débito, a recusa costuma acontecer por saldo insuficiente na conta corrente, senha incorreta ou alguma instabilidade temporária no aplicativo do seu banco.',
        "pergunta_seguinte": 'Você deseja conhecer as nossas formas de pagamento alternativas? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'recusado_pix',
        "prioridade": 2,
        "palavras": 'pix recusado,erro no pix,pix não vai,pix nao vai,pix dando erro,não consigo pagar no pix,nao consigo pagar no pix,falha no pix,pix foi falhou,pix foi recusado,pix recusou,pix não funciona,pix nao funciona,qr code não funciona,qr code nao funciona,copia e cola não funciona,copia e cola nao funciona,chave pix errada,pix expirou,qr code expirou,código pix expirou,codigo pix expirou,pix deu erro,erro ao pagar pix,não consigo fazer pix,nao consigo fazer pix',
        "resposta": 'Ih, que estranho! 💸 O Pix pode falhar se o código "Copia e Cola" ou o QR Code já tiverem expirado, se houver instabilidade no Banco Central ou se você atingiu o seu limite diário de transferências do banco.',
        "pergunta_seguinte": 'Você deseja conhecer as nossas formas de pagamento alternativas? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'cobranca_duplicada',
        "prioridade": 2,
        "palavras": 'cobrou duas vezes,cobrança duplicada,cobranca duplicada,cobrou duplo,cobrou a mais,duas vezes no cartao,duas cobranças,duas cobrancas,pagamento duplicado,cobrou em dobro,pagou duas vezes,paguei duas vezes,passou duas vezes,passou o cartão duas vezes,passou o cartao duas vezes,fui cobrado duas vezes,fui cobrada duas vezes,debitou duas vezes,debitou em dobro,cobrou errado,valor errado na fatura,valor duplicado',
        "resposta": "Se você viu duas cobranças no app do seu cartão, não se preocupe: geralmente uma delas é apenas a 'reserva de limite' do banco e sumirá em até 72h. Se ambas forem confirmadas na fatura, nossa equipe faz o estorno imediato.",
        "pergunta_seguinte": 'Deseja que eu te transfira para um atendente humano do Financeiro? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'comprovante',
        "prioridade": 4,
        "palavras": 'comprovante,enviar comprovante,mandar comprovante,anexo,foto do pagamento,ja paguei,já paguei,pagamento feito,pagamento realizado,pagamento efetuado,fiz o pagamento,efetuei o pagamento,realizei o pagamento,já efetuei o pagamento,já realizei o pagamento,paguei,paguei ja,paguei já,já foi o pix,pix foi,já mandei o pix,mandei o pix,fiz o pix,o pix foi,confirmação de pagamento,pagamento confirmado,quero enviar comprovante,posso enviar comprovante',
        "resposta": 'Para pagamentos via Pix ou Cartão, a aprovação em nosso sistema é 100% automática e leva poucos minutos! Não há necessidade de nos enviar o comprovante. 🚀',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'alterar_pagamento',
        "prioridade": 5,
        "palavras": 'mudar pagamento,alterar pagamento,trocar cartao,trocar cartão,quero pagar de outro jeito,mudar para pix,trocar forma de pagamento,alterar forma de pagamento,mudar forma de pagamento,trocar método de pagamento,alterar método de pagamento,mudar método de pagamento,quero pagar de outra forma,pagar diferente,mudar o pagamento,alterar o pagamento,trocar o pagamento,posso mudar a forma de pagamento,dá pra mudar o pagamento,da pra mudar o pagamento',
        "resposta": 'Por motivos de segurança e integração fiscal, após o pedido ser finalizado não conseguimos alterar a forma de pagamento.',
        "pergunta_seguinte": 'Deseja que eu te ajude a cancelar o pedido atual para você refazer a compra? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'contestacao_fraude',
        "prioridade": 2,
        "palavras": 'não reconheço,nao reconheco,contestou,contestar,fraude,cobrança indevida,cobranca indevida,cartao clonado,cartão clonado,clonaram meu cartão,clonaram meu cartao,compra que não fiz,compra que nao fiz,compra indevida,compra não autorizada,compra nao autorizada,não autorizei,nao autorizei,fui hackeado,hacker,dados roubados,conta invadida,alguém usou meu cartão,alguem usou meu cartao,cobrança estranha,cobranca estranha,cobrança desconhecida,cobranca desconhecida',
        "resposta": 'Segurança é assunto sério por aqui. Se você identificou uma cobrança da FashionFlow que não reconhece, precisamos isolar o seu caso imediatamente para análise do setor de segurança.',
        "pergunta_seguinte": 'Posso te direcionar agora para um especialista humano de segurança financeira? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'agradecimento',
        "prioridade": 1,
        "palavras": 'obrigado,obrigada,valeu,vlw,grato,grata,obg,mt obg,muito obrigado,muito obrigada,thanks,thank you,agradeço,agradeço muito,agradeço demais,muito grato,muito grata,te agradeço,agradecido,agradecida,obrigadão,obrigadona',
        "resposta": 'Fico feliz em poder ajudar! 😊 Se tiver mais alguma dúvida, é só chamar!',
        "pergunta_seguinte": 'Posso te ajudar com mais alguma coisa?',
        "encerrar": '',
    },
    {
        "tag": 'elogios',
        "prioridade": 2,
        "palavras": 'gostei,adorei,amei,maravilhoso,ótimo,otimo,perfeito,excelente,nota 10,nota dez,incrível,incrivel,sensacional,top,tops,muito bom,muito boa,show,showzasso,showzaço,demais,irado,irada,daora,da hora,dahora,muito top,muito show,que bom,que ótimo,que otimo,que legal,legal,maneiro,maneira,bacana,que bacana,adorei o atendimento,amei o atendimento,muito bom o atendimento,nota 10 no atendimento,parabéns,parabens,ótimo atendimento,otimo atendimento,excelente atendimento,atendimento ótimo,atendimento excelente,loja boa,loja ótima,loja top,melhor loja,amei a loja,adorei a loja',
        "resposta": 'Ficamos muito felizes em saber disso! 😊🎉 Sua satisfação é tudo pra gente. Se precisar de qualquer coisa, é só chamar!',
        "pergunta_seguinte": 'Posso te ajudar com mais alguma coisa?',
        "encerrar": '',
    },
    {
        "tag": 'reclamacoes',
        "prioridade": 2,
        "palavras": 'não gostei,nao gostei,odiei,péssimo,pessimo,ruim,nota 0,nota zero,horrível,horrivel,terrível,terrivel,péssimo atendimento,pessimo atendimento,que droga,que merda,ridículo,ridiculo,absurdo,uma vergonha,vergonhoso,lamentável,lamentavel,decepcionante,decepcionei,decepcionado,decepcionada,fui mal atendido,fui mal atendida,atendimento ruim,atendimento horrível,atendimento horrivel,loja ruim,loja péssima,loja pessima,pior loja,nunca mais volto,não volto mais,nao volto mais,péssima experiência,pessima experiencia,experiência horrível,experiencia horrivel,que raiva,tô com raiva,to com raiva,insatisfeito,insatisfeita,frustrado,frustrada',
        "resposta": 'Lamentamos muito que sua experiência não tenha sido boa. 😔 Isso é sério pra gente e queremos resolver!',
        "pergunta_seguinte": 'Posso te direcionar para um atendente humano para resolvermos isso juntos? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'cancelamento',
        "prioridade": 2,
        "palavras": 'cancelar,cancelamento,quero cancelar,cancelar pedido,cancelar compra,desfazer pedido,desfazer compra,não quero mais,nao quero mais,desistir,desisti,mudei de ideia,mudei de ideia do pedido,quero desistir,arrependido,arrependida,me arrependi,quero cancelar minha compra,posso cancelar,da pra cancelar,dá pra cancelar,como cancelo,como cancelar',
        "resposta": 'Entendido! Pedidos podem ser cancelados sem custo antes do envio. Após o envio, é necessário solicitar a devolução quando o produto chegar.',
        "pergunta_seguinte": 'Deseja que eu verifique o status do seu pedido para ver se ainda é possível cancelar? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'troca',
        "prioridade": 2,
        "palavras": 'troca,trocar,troca de produto,trocar produto,quero trocar,produto errado,recebi errado,tamanho errado,cor errada,modelo errado,veio errado,quero outro tamanho,quero outra cor,quero outro modelo,produto diferente do que pedi,diferente do pedido,não era o que eu pedi,nao era o que eu pedi,quero trocar por outro,posso trocar,dá pra trocar,da pra trocar,como faço pra trocar,como trocar,política de troca,politica de troca,prazo para troca,prazo de troca',
        "resposta": 'Aceitamos trocas em até 30 dias após o recebimento do produto, desde que esteja sem uso e com a etiqueta original.',
        "pergunta_seguinte": 'Deseja iniciar o processo de troca agora? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'rastreamento',
        "prioridade": 4,
        "palavras": 'rastrear,rastreamento,rastreio,código de rastreio,codigo de rastreio,código de rastreamento,codigo de rastreamento,onde está meu pedido,onde esta meu pedido,status do pedido,meu pedido,meu pedido onde está,meu pedido onde esta,acompanhar pedido,acompanhar entrega,pedido sumiu,pedido não chegou,nao chegou,não chegou,cadê meu pedido,cade meu pedido,quando chega meu pedido,atrasou,entrega atrasada,pedido atrasado,passou o prazo,passou a data,não foi entregue,nao foi entregue,não entregaram,nao entregaram',
        "resposta": 'Você pode rastrear seu pedido pelo código de rastreio enviado por e-mail após a postagem. 🔍',
        "pergunta_seguinte": 'Deseja que eu te ajude a verificar o status do seu pedido agora? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'retirada_local',
        "prioridade": 8,
        "palavras": 'retirada,retirar,retirar na loja,buscar na loja,pegar na loja,retirada no local,buscar pessoalmente,retirar pessoalmente,posso retirar,tem retirada,retirada disponível,retirada disponivel,pickup,pegar pessoalmente,retirar eu mesmo,retirar eu mesma,quero retirar,prefiro retirar,endereço da loja,endereco da loja,onde fica a loja,onde é a loja,onde e a loja,loja física,loja fisica,endereço,endereco',
        "resposta": 'Sim! Temos opção de retirada no local! 🏬 Após a confirmação do pedido, basta comparecer à nossa loja com o comprovante.',
        "pergunta_seguinte": 'Deseja o endereço completo da nossa loja? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'produto_indisponivel',
        "prioridade": 9,
        "palavras": 'esgotado,sem estoque,fora de estoque,indisponível,indisponivel,produto indisponível,produto indisponivel,não tem mais,nao tem mais,acabou,acabou o estoque,quando volta,quando tem,quando terá,quando tera,quando repõe,quando repoe,previsão de estoque,previsao de estoque,volta ao estoque,vai ter mais,vai repor,como saber quando volta,avisa quando tiver',
        "resposta": 'Que pena que esse item está esgotado! 😕 Mas fique de olho, nosso estoque é atualizado constantemente!',
        "pergunta_seguinte": 'Deseja que a gente te avise por e-mail quando o produto voltar ao estoque? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'tamanho',
        "prioridade": 9,
        "palavras": 'tamanho,tamanhos,grade,tabela de medidas,tabela de tamanhos,qual tamanho,que tamanho,meu tamanho,tamanho certo,tamanho correto,como saber meu tamanho,como medir,medidas,medida,tamanho P,tamanho M,tamanho G,tamanho GG,PP,P,M,G,GG,XG,XGG,36,38,40,42,44,46,48,50,guide de tamanho,guia de tamanhos,qual tamanho eu uso,qual tamanho comprar',
        "resposta": 'Temos uma tabela de medidas completa em nosso site para te ajudar a escolher o tamanho ideal! 📏',
        "pergunta_seguinte": 'Deseja que eu te explique como tirar suas medidas corretamente? (s/n)',
        "encerrar": '',
    },
    {
        "tag": 'duvidas_gerais',
        "prioridade": 10,
        "palavras": 'duvida,dúvida,dúvida geral,duvidas gerais,pergunta,perguntas,dúvida comum,dúvidas comuns,dúvida frequente,dúvidas frequentes,tenho uma dúvida,tenho uma duvida,queria perguntar,posso perguntar,queria tirar uma dúvida,queria tirar uma duvida,tô com dúvida,to com duvida,fiquei com dúvida,fiquei com duvida,não entendi,nao entendi,pode explicar,me explica,como funciona,não sei,nao sei',
        "resposta": 'Claro, estou aqui pra isso! 😊 Pode perguntar à vontade que faço o possível pra te ajudar.',
        "pergunta_seguinte": '',
        "encerrar": '',
    },
    {
        "tag": 'atendimento_humano',
        "prioridade": 10,
        "palavras": 'atendente,humano,pessoa,falar com alguém,falar com alguem,quero falar com atendente,quero falar com uma pessoa,me passa pra um humano,falar com o suporte,suporte humano,atendimento humano,não quero falar com robô,nao quero falar com robo,não quero robô,nao quero robo,quero atendimento humano,me transfere,me transfere para atendente,quero ser transferido,quero ser transferida',
        "resposta": 'Sem problemas! Vou te conectar com um de nossos atendentes humanos. 👤',
        "pergunta_seguinte": 'Pode me informar rapidinho qual é o assunto para eu direcionar ao setor certo? (s/n)',
        "encerrar": '',
    },
]

with open("base_conhecimento.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=[
                            "tag", "prioridade", "palavras", "resposta", "pergunta_seguinte", "encerrar"])
    writer.writeheader()
    writer.writerows(intencoes)
print("✨ Arquivo base_conhecimento.csv gerado com sucesso!")
