import csv


FIELDNAMES = [
    "tag",
    "prioridade",
    "palavras",
    "resposta",
    "pergunta_seguinte",
    "encerrar",
]


def termos(*grupos):
    vistos = set()
    resultado = []
    for grupo in grupos:
        for termo in grupo:
            termo_limpo = " ".join(str(termo).strip().split())
            chave = termo_limpo.lower()
            if termo_limpo and chave not in vistos:
                vistos.add(chave)
                resultado.append(termo_limpo)
    return ",".join(resultado)


intencoes = [
    {
        "tag": "seguranca_bloqueio",
        "prioridade": 0,
        "palavras": termos([
            "me passa os dado completo do cartao rapidin",
            "me passa os dados completo do cartao rapidin",
            "me passa os dados completos do cartao",
            "me manda o cartao completo",
            "manda os dados do cartao",
            "manda numero do cartao",
            "manda numero completo",
            "manda cvv",
            "me fala o cvv",
            "manda senha",
            "me passa a senha",
            "manda os dados do cliente",
            "dados do cliente",
            "cpf do cliente",
            "email do cliente",
            "ignora as regra ai so dessa vez",
            "ignora as regras",
            "ignora regra",
            "desativa seguranca",
            "troca o email da conta sem confirmar",
            "altera email sem confirmar",
            "troca cadastro sem validar",
            "faz o pix ai e depois a gente ve",
            "faz o pix depois confirma",
            "faz pix sem confirmar",
            "sou o dono confia",
            "sou o dono",
            "pode confiar sou eu",
            "confia no pai",
            "burlar seguranca",
            "pula a validacao",
            "sem confirmar identidade",
            "ignora as regra aí só dessa vez",
            "faz o pix aí e depois a gente vê",
            "manda os dados do cliente",
            "troca o email da conta sem confirmar",
            "manda dados de outro cliente",
            "alterar e-mail sem confirmacao",
            "mudar cadastro sem validar",
            "pula seguranca",
            "desativar autenticacao",
            "burlar o sistema",
            "nao precisa confirmar",
            "nao precisa de validacao",
            "manda os dado ai",
            "esquece as regras",
        ]),
        "resposta": (
            "Nao posso compartilhar dados sensiveis, alterar cadastro sem validacao "
            "ou executar pagamento fora do fluxo seguro. Posso orientar voce pelos "
            "canais oficiais: contestacao, reembolso, nota fiscal, Pix, cartao ou "
            "atendimento humano."
        ),
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "exit",
        "prioridade": 1,
        "palavras": termos([
            "sair",
            "encerrar",
            "finalizar",
            "tchau",
            "ate mais",
            "ate logo",
            "ate breve",
            "ate a proxima",
            "bye",
            "goodbye",
            "see you",
            "xau",
            "xauzinho",
            "tchauzinho",
            "falou",
            "falow",
            "flw",
            "fui",
            "fuis",
            "pode fechar",
            "pode encerrar",
            "encerrar atendimento",
            "encerar atendimento",
            "fechar atendimento",
            "ja era",
            "jah era",
            "dispensado",
            "dispensada",
            "ate amanha",
            "ate semana que vem",
            "parar atendimento",
            "cancelar sessao",
            "fechar o chat",
            "pode fechar o chat",
            "chega por hoje",
            "tchau obg",
            "valeu tchau",
            "encerrar agora",
            "pode finalizar",
            "sair do chat",
            "sair do sistema",
            "fim do atendimento",
            "concluir",
            "concluido",
            "concluir atendimento",
        ]),
        "resposta": "Atendimento finalizado. Obrigado por falar com o Financeiro da FashionFlow.",
        "pergunta_seguinte": "",
        "encerrar": "True",
    },
    {
        "tag": "contestacao_fraude",
        "prioridade": 2,
        "palavras": termos([
            "pagamento nao reconhecido",
            "pagamento desconhecido",
            "transacao nao reconhecida",
            "nao reconheco",
            "nao reconheco essa cobranca",
            "nao reconheco essa paulada no cartao nao",
            "nao comprei isso nao meu rei",
            "eu nao fiz essa compra",
            "nunca comprei isso",
            "nao fui eu que comprei",
            "nao autorizei nada disso ai nao",
            "nao autorizei",
            "sem minha autorizacao",
            "compra nao autorizada",
            "compra que nao fiz",
            "compra indevida",
            "cobranca desconhecida",
            "cobranca estranha",
            "cobranca fantasma",
            "mano caiu uma cobranca fantasma aq",
            "caiu cobranca fantasma",
            "tiraram dinheiro da minha conta na maciota foi",
            "tiraram dinheiro da minha conta do nada vei",
            "sumiu dinheiro da minha conta",
            "debitaram sem eu comprar",
            "isso aqui ta parecendo golpe",
            "golpe",
            "fraude",
            "cartao clonado",
            "cartao clonado foi",
            "voces clonaram meu cartao foi",
            "clonaram meu cartao",
            "usaram meu cartao",
            "alguem usou meu cartao",
            "tem uma cobranca 3h da manha",
            "eu tava dormindo",
            "como q eu compro algo sem comprar",
            "isso ai foi bug ou assalto",
            "quero contestar essa paulada no cartao",
            "contestar",
            "contestacao",
            "cobrou mas o pedido evaporou",
            "cobraram e o pedido sumiu",
            "cobranca perdida",
            "essa cobranca ai ta mais perdida que eu",
            "ces tao me roubando",
            "caiu um ngc aqui q nem sei oq e",
            "fralde",
            "clunaram",
            "rackeado",
            "haquer",
            "hacker",
            "conta invadida",
            "dados roubados",
            "ces tao me taxando do nada",
            "cês tão me taxando do nada",
            "isso aqui ta parecendo golpe hein",
            "isso aqui tá parecendo golpe hein",
            "tem uma cobranca 3h da manha kkkkk eu tava dormindo",
            "tem uma cobrança 3h da manhã kkkkk eu tava dormindo",
            "ces tao me roubando pq caiu um ngc aqui q nem sei oq e",
            "cês tão me roubando pq caiu um ngc aqui q nem sei oq é",
            "veio uma cobranca torta aqui meu patrao",
            "veio uma cobrança torta aqui meu patrão",
            "me roubaram",
            "fui roubado",
            "fui roubada",
            "cobranca indevida",
            "uso indevido",
            "meu cartao foi clonado",
            "clonagem de cartao",
            "hackearam minha conta",
            "compras nao reconhecidas",
            "nao fiz essa compra",
        ]),
        "resposta": (
            "Isso pode envolver seguranca financeira. Para proteger seus dados, nao vou "
            "pedir numero completo de cartao nem senha por aqui. Vou direcionar o caso "
            "para contestacao com prioridade."
        ),
        "pergunta_seguinte": "Posso te transferir agora para um especialista de seguranca financeira? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "cobranca_duplicada_valor_incorreto",
        "prioridade": 3,
        "palavras": termos([
            "cobranca duplicada",
            "cobranca dupla",
            "cobranca repetida",
            "cobrou duas vezes",
            "cobrou 2 vezes",
            "cobraram duas vez",
            "cobraram 2x",
            "oxi cobraram duas vez aqui pae",
            "duas cobrancas",
            "duas vezes no cartao",
            "pagamento duplicado",
            "cobrou em dobro",
            "debitou duas vezes",
            "debitou em dobro",
            "valor incorreto",
            "valor errado",
            "valor errado na fatura",
            "cobrou errado",
            "cobrou a mais",
            "valor maior",
            "valor maior que o combinado",
            "preco diferente",
            "preco errado",
            "preco veio diferente",
            "desconto nao entrou",
            "cupom nao aplicou",
            "cobranca indevida",
            "cobranca torta",
            "veio uma cobranca torta aqui meu patrao",
            "veio um debito torto aqui explica isso ai",
            "ces tao me taxando do nada",
            "taxando do nada",
            "que valor aleatorio e esse aq",
            "valor aleatorio",
            "cade a logica dessa fatura aqui",
            "me explica essa matematica criminosa ai",
            "meu valor era 29 e veio 47",
            "meteram dlc",
            "fizeram assinatura escondida",
            "assinatura escondida",
            "ta descontando todo mes e eu nem uso",
            "cobrando plano premium",
            "plano premium sendo q eu sou liso",
            "to sendo cobrado por existir agr",
            "essa fatura veio possuida",
            "pq meu boleto multiplicou",
            "qual genio calculou essa cobranca",
            "essa taxa saiu de onde do multiverso",
            "taxa saiu de onde",
            "inventando taxa",
            "ces tao inventando taxa agora",
            "pq tao me cobrando um ngc cancelado",
            "cobrando coisa cancelada",
            "cobranca de cancelado",
            "fatura errada",
            "cobranca incorreta",
            "valor incorreto da compra",
            "valor da compra errado",
            "pedido veio mais caro",
            "cobraram assinatura cancelada",
            "assinatura cancelada cobrando",
            "boleto multiplicou",
            "cobro duas vzs",
            "cobrou 2 vzs",
            "dobro",
            "fatura duplicada",
            "oxi cobraram duas vez aqui pae 🤡",
            "ta cobrando plano premium sendo q eu sou liso",
            "meu valor era 29 e veio 47 meteram dlc",
            "meu valor era 29 e veio 47, meteram dlc?",
            "fizeram assinatura escondida ne safados",
            "fizeram assinatura escondida né safados",
            "essa taxa saiu de onde do multiverso",
            "essa taxa saiu de onde do multiverso?",
            "cobrou dobrado",
            "veio duas vezes cobrado",
            "valor veio errado",
            "estao cobrando a mais",
            "fatura muito alta",
            "erro de calculo na fatura",
            "cobrou plano errado",
            "taxa indevida",
            "me taxaram errado",
            "cobranca extra",
        ]),
        "resposta": (
            "Entendi: parece uma cobranca duplicada ou valor incorreto. Em financeiro, "
            "o ideal e conferir pedido, data, valor e meio de pagamento antes de qualquer "
            "acao. Se houver duplicidade confirmada, o caminho correto e auditoria e estorno."
        ),
        "pergunta_seguinte": "Deseja que eu transfira para um atendente do Financeiro analisar a cobranca? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "conciliacao_pagamento",
        "prioridade": 4,
        "palavras": termos([
            "ja paguei",
            "ja foi pago",
            "eu ja paguei essa bomba vei",
            "paguei e nao constou",
            "pagamento nao constou",
            "pagamento nao caiu",
            "pagamento nao apareceu",
            "paguei e continuo inadimplente",
            "paguei e continua pendente",
            "paguei e ainda ta pendente",
            "meu banco aprovou mas vcs tao dizendo q nao",
            "banco aprovou",
            "o pix saiu e pra vcs sumiu misteriosamente",
            "pix saiu e sumiu",
            "pix saiu da conta",
            "pix debitou",
            "pagamento aprovado no banco",
            "aprovado no app do banco",
            "servico nem funcionou",
            "me cobraram mas o servico nem funcionou",
            "paguei mas nao liberou",
            "paguei e nao liberaram",
            "pedido nao liberou",
            "pagamento feito",
            "pagamento realizado",
            "pagamento efetuado",
            "fiz o pagamento",
            "efetuei o pagamento",
            "realizei o pagamento",
            "mandei o pix",
            "fiz o pix",
            "pix foi",
            "comprovante",
            "enviar comprovante",
            "mandar comprovante",
            "anexo",
            "foto do pagamento",
            "comporvante",
            "comporvnt",
            "ja paguei essa bomba",
            "dinheiro saiu da conta mas nao aprovou",
            "pix enviado mas nao consta",
            "fiz o pagamento mas continua pendente",
            "comprovante enviado",
            "meu saldo diminuiu e nao aprovou",
            "ja debitou do banco",
            "banco confirmou mas vcs nao",
            "paguei faz tempo",
            "boleto pago mas nao liberado",
            "meu pix sumiu",
        ]),
        "resposta": (
            "Se o banco aprovou e ainda nao constou na FashionFlow, precisamos tratar "
            "como conciliacao de pagamento. Confira se o pagamento foi para o pedido "
            "correto e aguarde alguns minutos; se persistir, um atendente valida pelo comprovante."
        ),
        "pergunta_seguinte": "Deseja falar com o Financeiro para conferir a conciliacao do pagamento? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "reembolso",
        "prioridade": 5,
        "palavras": termos([
            "reembolso",
            "reembolsar",
            "devolucao",
            "estornar",
            "estorno",
            "devolucoes",
            "estornos",
            "estornar pagamento",
            "estornar compra",
            "quero meu dinheiro de volta",
            "dinheiro de volta",
            "me devolve o dinheiro",
            "me devolve meu dinheiro antes q eu enlouqueeca",
            "devolve meu dinheiro",
            "cade minha grana",
            "quero meu pix de volta namoral",
            "pix de volta",
            "deu ruim ai no servico devolve a grana",
            "devolve a grana",
            "cancelei faz mo cota",
            "ate agora nada",
            "ate agora nadakkkkk",
            "cade meu reembolso pae",
            "cade meu reembolso",
            "voces estornam",
            "voces estornam ou so na proxima encarnacao",
            "o estorno foi de americanas",
            "quando cai o reembolso",
            "quando volta o dinheiro",
            "prazo do estorno",
            "prazo do reembolso",
            "rebolso",
            "reembolco",
            "rimbolso",
            "storno",
            "istorno",
            "devoluco",
            "rreembolso",
            "deu ruim ai no servico devolve a grana",
            "deu ruim aí no serviço, devolve a grana",
            "cancelei faz mo cota e ate agora nadakkkkk",
            "cancelei faz mó cota e até agora nadakkkkk",
            "voces estornam ou so na proxima encarnacao",
            "vocês estornam ou só na próxima encarnação?",
            "quero meu estorno logo",
            "devolva meu pix",
            "devolucao do valor",
            "estorno demorado",
            "cade o dinheiro do cancelamento",
            "quero estornar",
        ]),
        "resposta": (
            "Reembolsos por Pix costumam cair em ate 24h apos o estorno. No cartao, "
            "o prazo depende da operadora e pode aparecer na fatura atual ou seguinte."
        ),
        "pergunta_seguinte": "Deseja iniciar ou consultar um processo de reembolso agora? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "nota_fiscal",
        "prioridade": 6,
        "palavras": termos([
            "nota fiscal",
            "nf",
            "nfe",
            "nf-e",
            "nfce",
            "nfc-e",
            "comprovante fiscal",
            "nota da compra",
            "nota eletronica",
            "nota fiscal eletronica",
            "preciso da nota",
            "quero a nota fiscal",
            "onde esta minha nota",
            "nao recebi nota fiscal",
            "nota fiscal nao chegou",
            "manda a notinha ai chefe",
            "manda a nota",
            "manda nota fiscal",
            "notinha",
            "cade a nf dessa parada",
            "cade a nota",
            "preciso da nota pra ontem",
            "preciso da nfe",
            "tem como tirar nf no cpf da minha mae",
            "trocar cpf da nota",
            "alterar cpf da nota",
            "corrigir cpf da nota",
            "essa compra teve nota memo",
            "notiscl",
            "nota fiscl",
            "notafiscal",
            "nota eletronika",
            "manda a notinha ai chefe",
            "manda a notinha aí chefe",
            "cade a nf dessa parada",
            "cadê a nf dessa parada",
            "preciso da nota pra ontem slk",
            "tem como tirar nf no cpf da minha mae",
            "tem como tirar nf no cpf da minha mãe?",
            "essa compra teve nota memo",
            "essa compra teve nota memo?",
            "segunda via da nota",
            "emitir nota",
            "nota fiscal de servico",
            "danfe",
            "xml da nota",
            "cade meu comprovante fiscal",
        ]),
        "resposta": (
            "A NF-e e enviada automaticamente para o e-mail cadastrado quando o pagamento "
            "e faturado. Tambem fica disponivel em Meus Pedidos. Por seguranca fiscal, "
            "alteracao de CPF/CNPJ so pode ocorrer conforme regras de faturamento."
        ),
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "recusado_cartao_credito",
        "prioridade": 7,
        "palavras": termos([
            "credito recusado",
            "recusou credito",
            "erro no credito",
            "cartao de credito nao passou",
            "credito foi recusado",
            "cartao recusado",
            "nao aprovou o credito",
            "pagamento recusado credito",
            "deu erro no credito",
            "cartao nao passou",
            "nao foi no credito",
            "recuzado",
            "crdito recusado",
            "nao pacou",
            "naopassou",
            "ero cartao",
            "nao quer passar no credito",
            "cartao de credito bloqueado",
            "credito dando erro",
            "operadora recusou",
            "nao aceitou meu cartao de credito",
            "erro ao processar credito",
        ]),
        "resposta": (
            "Cartoes de credito podem ser recusados por limite, dados digitados incorretamente "
            "ou bloqueio preventivo do banco."
        ),
        "pergunta_seguinte": "Deseja conhecer formas de pagamento alternativas? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "recusado_cartao_debito",
        "prioridade": 7,
        "palavras": termos([
            "debito recusado",
            "recusou debito",
            "erro no debito",
            "cartao de debito nao passou",
            "debito foi recusado",
            "nao foi no debito",
            "deu erro no debito",
            "pagamento recusado debito",
            "debto recusado",
            "errou debito",
            "nao quer passar no debito",
            "cartao de debito dando erro",
            "debito nao aceito",
            "banco barrou o debito",
            "falha no debito",
        ]),
        "resposta": (
            "No debito, a recusa costuma acontecer por saldo insuficiente, senha incorreta "
            "ou instabilidade temporaria do banco."
        ),
        "pergunta_seguinte": "Deseja conhecer formas de pagamento alternativas? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "recusado_pix",
        "prioridade": 7,
        "palavras": termos([
            "pix recusado",
            "erro no pix",
            "pix nao vai",
            "pix dando erro",
            "nao consigo pagar no pix",
            "falha no pix",
            "pix foi recusado",
            "pix nao funciona",
            "qr code nao funciona",
            "copia e cola nao funciona",
            "chave pix errada",
            "pix expirou",
            "qr code expirou",
            "codigo pix expirou",
            "pix deu erro",
            "erro ao pagar pix",
            "nao consigo fazer pix",
            "pics recusado",
            "qr cod falhou",
            "expirow",
            "nao consigo transferir o pix",
            "sistema do pix fora do ar",
            "pix falhou",
            "erro no pagamento pix",
            "banco nao envia o pix",
            "chave pix invalida",
            "qr code nao carrega",
        ]),
        "resposta": (
            "O Pix pode falhar por QR Code expirado, limite diario do banco, instabilidade "
            "ou codigo copia e cola incorreto."
        ),
        "pergunta_seguinte": "Deseja conhecer formas de pagamento alternativas? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "forma_pagamento",
        "prioridade": 8,
        "palavras": termos([
            "formas de pagamento",
            "forma de pagamento",
            "quais formas",
            "como posso pagar",
            "aceita o que",
            "aceita oq",
            "como pagar",
            "formas de pagamento aceitas",
            "formas de pagamento disponiveis",
            "o que voces aceitam",
            "quais sao as formas",
            "meios de pagamento",
            "opcoes de pagamento",
            "posso pagar de que forma",
            "meo de pagament",
            "pagemento",
            "fomas de pagamento",
            "paguamento",
            "pagto",
            "meios aceitos",
            "quais cartoes aceitam",
            "formas de quitar",
            "como posso pagar o pedido",
            "opcoes de acerto",
        ]),
        "resposta": (
            "Aceitamos Pix com desconto, cartao de credito/debito Visa e Mastercard "
            "e dinheiro somente para retirada no local."
        ),
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "pix",
        "prioridade": 9,
        "palavras": termos([
            "pix",
            "picks",
            "pagar no pix",
            "pagamento pix",
            "chave pix",
            "pagar with pix",
            "fazer pix",
            "transferencia pix",
            "qual a chave pix",
            "me passa a chave pix",
            "me manda a chave pix",
            "qr code pix",
            "qr code",
            "copia e cola pix",
            "copia e cola",
            "pagar via pix",
            "pix instantaneo",
            "aprovacao pix",
            "quanto tempo o pix",
            "pix aprova na hora",
            "pics",
            "pic",
            "pixs",
            "piz",
            "piss",
            "pich",
            "pikz",
            "xave pix",
            "copiae-cola",
            "qr-code",
            "pagamento instantaneo",
            "pagar por pix",
            "chave aleatoria",
            "copia e cola do pix",
            "codigo do pix",
            "gerar pix",
        ]),
        "resposta": "Temos pagamento via Pix com aprovacao rapida e 5% de desconto.",
        "pergunta_seguinte": "Deseja gerar a chave Pix para o pedido? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "credito",
        "prioridade": 10,
        "palavras": termos([
            "credito",
            "cartao de credito",
            "pagar no credito",
            "pagar com credito",
            "cartao credito",
            "no credito",
            "com credito",
            "passar no credito",
            "credto",
            "creidto",
            "crdeto",
            "cartao de creidto",
            "cretido",
            "credidto",
            "pagar com cartao de credito",
            "passa no credito",
            "no cartao de credito",
            "quero usar credito",
        ]),
        "resposta": "Pagamento no credito disponivel em ate 12x sem juros.",
        "pergunta_seguinte": "Qual a bandeira do cartao e quantidade de parcelas? (Ex: Visa, 3x)",
        "encerrar": "",
    },
    {
        "tag": "debito",
        "prioridade": 10,
        "palavras": termos([
            "debito",
            "cartao de debito",
            "pagar no debito",
            "pagar com debito",
            "cartao debito",
            "no debito",
            "com debito",
            "passar no debito",
            "debto",
            "debeto",
            "devito",
            "cartao de debto",
            "pagar com cartao de debito",
            "passa no debito",
            "no cartao de debito",
            "quero usar debito",
        ]),
        "resposta": "Pagamento no debito disponivel nas bandeiras Visa e Mastercard.",
        "pergunta_seguinte": "Qual a bandeira do seu cartao de debito? (Ex: Visa)",
        "encerrar": "",
    },
    {
        "tag": "parcela",
        "prioridade": 11,
        "palavras": termos([
            "parcelar",
            "parcela",
            "parcelas",
            "vezes",
            "pagar em parcelas",
            "dividir em parcelas",
            "pagar em vezes",
            "parcelamento",
            "quantidade de parcelas",
            "quantas vezes",
            "quantas parcelas",
            "em quantas vezes",
            "tem parcelamento",
            "posso parcelar",
            "da pra parcelar",
            "como parcelar",
            "juros",
            "sem juros",
            "12x",
            "12 vezes",
            "parc_ela",
            "vzs",
            "parcelameno",
            "parcelamento sem juros",
            "dividir o valor",
            "parcelado",
            "quantas vezes divide",
            "parcela em quanto",
            "tem juros se parcelar",
        ]),
        "resposta": "Parcelamento disponivel in ate 12x sem juros no credito.",
        "pergunta_seguinte": "Qual a bandeira do cartao e quantidade de parcelas? (Ex: Visa, 3x)",
        "encerrar": "",
    },
    {
        "tag": "boleto",
        "prioridade": 12,
        "palavras": termos([
            "boleto",
            "boletu",
            "boleto bancario",
            "pagar boleto",
            "pagar com boleto",
            "gerar boleto",
            "tem boleto",
            "aceita boleto",
            "quero pagar no boleto",
            "posso pagar no boleto",
            "pagamento por boleto",
            "bolheto",
            "boledo",
            "baleto",
            "boleto bancao",
            "blet",
            "gerar o boleto",
            "codigo de barras",
            "pagamento por boleto bancario",
            "boleto em pdf",
            "mandar boleto",
        ]),
        "resposta": "Nao aceitamos boleto bancario. Voce pode pagar via Pix ou cartao.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "pagamento_misto",
        "prioridade": 12,
        "palavras": termos([
            "pagamento misto",
            "misto",
            "dois cartoes",
            "dividir pagamento",
            "pix e cartao",
            "pagar com dois cartoes",
            "pagar com pix e cartao",
            "pix e debito",
            "pix e credito",
            "dividir em dois cartoes",
            "pagar metade no pix",
            "mais de um cartao",
            "msto",
            "paguamento misto",
            "pagmento mixto",
            "dividir em 2 cartoes",
            "dividir em dois meios",
            "metade pix metade cartao",
            "pagar com duas formas",
            "combinar pagamentos",
        ]),
        "resposta": "No momento, nosso checkout nao suporta pagamento misto ou divisao em dois cartoes.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "bandeiras",
        "prioridade": 13,
        "palavras": termos([
            "bandeira",
            "bandeiras",
            "visa",
            "master",
            "mastercard",
            "aceitam visa",
            "aceitam mastercard",
            "aceita elo",
            "aceita hipercard",
            "amex",
            "american express",
            "bandera",
            "bandira",
            "viza",
            "mestre",
            "mastercrd",
            "eloo",
            "ipercard",
            "quais bandeiras",
            "aceita elo",
            "hipercard aceita",
            "bandeira do cartao",
        ]),
        "resposta": "Aceitamos Visa e Mastercard para pagamentos por cartao.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "desconto",
        "prioridade": 14,
        "palavras": termos([
            "cupom",
            "desconto",
            "voucher",
            "promocao",
            "descontos",
            "cupons",
            "tem desconto",
            "tem promocao",
            "codigo de desconto",
            "cupom de desconto",
            "quero desconto",
            "me da um desconto",
            "oferta",
            "liquidacao",
            "sale",
            "black friday",
            "preco especial",
            "disconto",
            "descomto",
            "pormocao",
            "vauxer",
            "cupom ativo",
            "desconto na primeira compra",
            "codigo promocional",
            "ganhar desconto",
            "algum cupom",
        ]),
        "resposta": "Promocao ativa: 5% de desconto para compras via Pix.",
        "pergunta_seguinte": "Deseja gerar a chave Pix agora? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "isencao_juros_multas",
        "prioridade": 4,
        "palavras": termos([
            "vcs vao me cobrar juros por um erro do app",
            "tira essa multa ai eu tentei pagar ontem",
            "quero o estorno do juro que veio no boleto",
            "por que cobrou taxa de atraso se o pix caiu no dia",
            "cobraram juros indevido",
            "multa indevida",
            "juros indevido",
            "taxa de atraso indevida",
            "juros por erro do sistema",
            "multa por erro do app",
            "nao quero pagar multa",
            "isencao de juros",
            "isencao de multa",
            "tirar juros",
            "remover multa",
            "estornar juros",
            "estornar multa",
            "vcs vao me cobrar juros por um erro do app",
            "tira essa multa ai eu tentei pagar ontem",
            "quero o estorno do juro que veio no boleto",
            "por que cobrou taxa de atraso se o pix caiu no dia",
            "remover juros",
            "tirar multa",
            "cancelar multa de atraso",
            "nao quero pagar juros",
            "taxa de atraso injusta",
            "estornar multa",
            "reclamar de juros",
            "cobraram multa errado",
        ]),
        "resposta": "Se o atraso no pagamento ocorreu por instabilidade do nosso sistema, podemos abrir uma analise para contestacao e isencao de juros ou multas.",
        "pergunta_seguinte": "Deseja que eu abra uma solicitacao de analise de juros agora? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "negociacao_divida",
        "prioridade": 5,
        "palavras": termos([
            "estou inadimplente com vcs",
            "quero limpar meu nome",
            "como faco pra parcelar minha divida",
            "tem alguma pendencia financeira no meu cpf",
            "tenho divida com voces",
            "meu nome esta sujo",
            "nome negativado",
            "negociar divida",
            "acordo de pagamento",
            "parcelar debito",
            "regularizar pendencia",
            "pendencia financeira",
            "restricao no cpf",
            "divida em aberto",
            "boleto atrasado",
            "quero fazer acordo",
            "estou inadimplente com vcs",
            "quero limpar meu nome",
            "como faco pra parcelar minha divida",
            "tem alguma pendencia financeira no meu cpf",
            "renegociar divida",
            "acordo financeiro",
            "quitar meus debitos",
            "nome no serasa",
            "parcelamento de divida",
            "tenho restricao no nome",
            "como pagar o que devo",
            "fazer um acordo",
        ]),
        "resposta": "Para regularizar pendencias financeiras, consultar restricoes ou realizar um acordo de parcelamento de debito, vou te direcionar para o setor de cobranca.",
        "pergunta_seguinte": "Deseja falar com o setor de acordos e negociacao agora? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "status_pagamento",
        "prioridade": 15,
        "palavras": termos([
            "status do pagamento",
            "situacao do pagamento",
            "situacao do pagto",
            "pagamento pendente",
            "pagamento em analise",
            "pagamento aprovado",
            "pagamento confirmado",
            "pedido aprovado",
            "pedido pendente",
            "compra aprovada",
            "compra pendente",
            "meu pagamento aprovou",
            "meu pagamento foi aprovado",
            "pagamento ta em analise",
            "pagamento em análise",
            "ta pendente",
            "ta em analise",
            "foi aprovado",
            "aprovou ou nao",
            "status pagto",
            "pagamento parado",
            "pedido parado",
            "ja confirmou o pagamento",
            "saber se foi aprovado",
            "minha compra ja aprovou",
            "verificar status de pagamento",
            "onde vejo se o pagamento caiu",
        ]),
        "resposta": (
            "Para status financeiro, confira primeiro a area Meus Pedidos. Pix costuma "
            "aprovar em poucos minutos; cartao pode ficar em analise antifraude antes da confirmacao."
        ),
        "pergunta_seguinte": "Se o banco ja aprovou e a FashionFlow ainda nao reconheceu, deseja falar com o Financeiro? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "link_pagamento",
        "prioridade": 8,
        "palavras": termos([
            "link de pagamento",
            "perdi o link",
            "manda o link de pagamento",
            "reenviar link",
            "link expirou",
            "checkout expirou",
            "pix expirou",
            "qr code expirou",
            "gerar novo pix",
            "gerar novo qr code",
            "novo link de pagamento",
            "segunda via do pagamento",
            "segunda via",
            "2 via",
            "2a via",
            "refazer pagamento",
            "pagar de novo",
            "nao consigo abrir o checkout",
            "checkout nao abre",
            "mande o link de novo",
            "link seguro",
            "gerar link",
            "link do checkout",
            "url de pagamento",
        ]),
        "resposta": (
            "Posso orientar a gerar uma nova tentativa de pagamento pelo checkout seguro. "
            "Nunca pague por chave enviada fora dos canais oficiais da FashionFlow."
        ),
        "pergunta_seguinte": "Deseja receber orientacao para gerar um novo pagamento seguro? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "extrato_historico",
        "prioridade": 6,
        "palavras": termos([
            "me passa tudo q vcs me cobraram desde o inicio ai",
            "quero ver meu historico de compras",
            "manda o meu extrato financeiro da conta",
            "quero a lista de tudo que ja paguei aqui",
            "extrato financeiro",
            "historico financeiro",
            "historico de pagamentos",
            "historico de transacoes",
            "lista de compras",
            "lista de pagamentos",
            "relatorio financeiro",
            "relatorio de compras",
            "tudo que paguei",
            "todas as cobrancas",
            "minhas transacoes",
            "me passa tudo q vcs me cobraram desde o inicio ai",
            "quero ver meu historico de compras",
            "manda o meu extrato financeiro da conta",
            "quero a lista de tudo que ja paguei aqui",
            "ver meu historico financeiro",
            "puxar extrato",
            "puxa meu historico ai",
            "relatorio de gastos",
            "comprovantes de pagamento",
            "onde vejo o extrato",
            "extrato de cobrancas",
            "meu historico",
        ]),
        "resposta": "Para consultar seu extrato ou historico completo de transacoes, voce pode acessar a aba Minha Conta ou solicitar o relatorio detalhado.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "alterar_vencimento",
        "prioridade": 8,
        "palavras": termos([
            "consigo mudar o dia do vencimento",
            "quero que o boleto venca todo dia 10",
            "tem como alterar a data de pagamento da assinatura",
            "quero pagar depois altera o vencimento ai",
            "mudar vencimento",
            "alterar vencimento",
            "trocar data de vencimento",
            "mudar data de pagamento",
            "alterar data de pagamento",
            "vencimento da assinatura",
            "boleto vencer dia 10",
            "boleto todo dia 10",
            "prorrogar vencimento",
            "pagar depois",
            "adiar vencimento",
            "consigo mudar o dia do vencimento",
            "quero que o boleto venca todo dia 10",
            "tem como alterar a data de pagamento da assinatura",
            "quero pagar depois altera o vencimento ai",
            "mudar data do boleto",
            "alterar dia de vencimento",
            "mudar vencimento da fatura",
            "trocar dia do pagamento",
            "alterar data de vencimento",
            "mudar dia que vence",
            "mudar o dia da cobranca",
        ]),
        "resposta": "A alteracao da data de vencimento de faturas ou assinaturas recorrentes pode ser feita uma vez a cada ciclo diretamente no painel de controle da sua conta.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "atualizar_metodo_pagamento",
        "prioridade": 8,
        "palavras": termos([
            "quero trocar o cartao de credito da assinatura",
            "como mudo a minha conta principal de pagamento",
            "meu cartao venceu onde coloco o novo",
            "remover cartao salvo da conta",
            "trocar cartao salvo",
            "atualizar cartao",
            "cartao vencido",
            "cartao expirou",
            "adicionar novo cartao",
            "incluir cartao",
            "excluir cartao",
            "apagar cartao",
            "mudar forma de pagamento da assinatura",
            "alterar pagamento da assinatura",
            "cartao da assinatura",
            "quero trocar o cartao de credito da assinatura",
            "como mudo a minha conta principal de pagamento",
            "meu cartao venceu onde coloco o novo",
            "remover cartao salvo da conta",
            "atualizar cartao de credito",
            "cadastrar novo cartao",
            "mudar forma de pagamento",
            "alterar cartao da assinatura",
            "trocar cartao salvo",
            "inserir novo cartao",
            "mudar cartao principal",
        ]),
        "resposta": "Para sua seguranca, a atualizacao, inclusao ou remocao de cartoes de credito salvos deve ser feita exclusivamente por voce na aba Formas de Pagamento do seu perfil.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "dados_bancarios_empresa",
        "prioridade": 3,
        "palavras": termos([
            "me passa o cnpj de vcs pra eu fazer o pix direto",
            "qual e a conta bancaria da fashionflow",
            "posso fazer ted me da os dados da conta",
            "passa a chave pix cnpj da empresa",
            "dados bancarios da empresa",
            "conta bancaria da loja",
            "cnpj para pix",
            "chave pix da empresa",
            "pix direto para empresa",
            "fazer ted",
            "fazer transferencia manual",
            "transferencia bancaria",
            "deposito em conta",
            "me passa a conta",
            "qual banco de voces",
            "me passa o cnpj de vcs pra eu fazer o pix direto",
            "qual e a conta bancaria da fashionflow",
            "posso fazer ted me da os dados da conta",
            "passa a chave pix cnpj da empresa",
            "dados bancarios da empresa",
            "qual e o cnpj",
            "agencia e conta da loja",
            "chave pix da loja",
            "dados para transferencia",
            "passa a conta juridica",
            "transferir direto para vcs",
        ]),
        "resposta": "Nao realizamos recebimentos por transferencia manual direta ou TED. Os pagamentos seguros devem ser feitos apenas via QR Code Pix ou Copia e Cola gerados no checkout.",
        "pergunta_seguinte": "Deseja que eu te oriente a gerar o codigo Pix oficial do seu pedido? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "dinheiro",
        "prioridade": 17,
        "palavras": termos([
            "dinheiro",
            "especie",
            "pagar com dinheiro",
            "pagar no dinheiro",
            "dineiro",
            "dindin",
            "grana",
            "cash",
            "troco",
            "aceita dinheiro",
            "cedola",
            "spece",
            "pagar em notas",
            "pagamento em papel",
            "dinheiro vivo",
            "aceita especie",
            "pagar na retirada",
        ]),
        "resposta": "Aceitamos dinheiro somente para retirada no local.",
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "fluxo_vago",
        "prioridade": 16,
        "palavras": termos([
            "quanto ficou",
            "qnt ficou",
            "qt ficou",
            "e agora",
            "oq eu faco agora",
            "o que eu faco agora",
            "o de ontem",
            "aquele de ontem",
            "aquela cobranca la",
            "aquela cobranca",
            "aquela fatura",
            "aquele pagamento",
            "manda de novo",
            "repete",
            "fala de novo",
            "nao entendi",
            "como assim",
            "qual deles",
            "nao sei qual escolher",
            "qual opcao",
            "o que houve",
            "me ajuda ai",
            "o que faço",
            "nao sei o que dizer",
            "e depois",
            "qual o proximo passo",
            "e agr",
        ]),
        "resposta": (
            "Para eu nao chutar em assunto financeiro, preciso de um pouco mais de contexto. "
            "Posso ajudar com: 1) cobranca incorreta, 2) pagamento nao reconhecido, "
            "3) pagamento que nao constou, 4) reembolso, 5) nota fiscal, 6) formas de pagamento, "
            "7) extrato, 8) status do pagamento ou 9) negociacao de divida."
        ),
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "elogios",
        "prioridade": 17,
        "palavras": termos([
            "gostei",
            "adorei",
            "amei",
            "maravilhoso",
            "otimo",
            "perfeito",
            "excelente",
            "nota 10",
            "nota dez",
            "incrivel",
            "sensacional",
            "top",
            "muito bom",
            "show",
            "daora",
            "da hora",
            "legal",
            "maneiro",
            "bacana",
            "parabens",
            "otimo atendimento",
            "excelente atendimento",
            "topzera",
            "semsacional",
            "amei o bot",
            "muito rapido",
            "atendimento excelente",
            "nota mil",
            "voces sao feras",
            "ajudou muito",
            "perfeito o atendimento",
        ]),
        "resposta": "Que bom saber disso. Fico feliz em ajudar no que for do Financeiro.",
        "pergunta_seguinte": "Quer consultar mais algum assunto financeiro?",
        "encerrar": "",
    },
    {
        "tag": "agradecimento",
        "prioridade": 18,
        "palavras": termos([
            "obrigado",
            "obrigada",
            "valeu",
            "vlw",
            "grato",
            "grata",
            "obg",
            "mt obg",
            "muito obrigado",
            "muito obrigada",
            "thanks",
            "thank you",
            "agradeco",
            "brigado",
            "obgda",
            "thnx",
            "valew",
            "valeuu",
            "tankiu",
            "gratidao",
            "tmj",
            "tmjj",
            "agradecido",
            "muitissimo obrigado",
            "valeu mesmo",
            "brigadao",
            "brigadaco",
            "obrigadissima",
            "obrigadissimo",
        ]),
        "resposta": "Disponha. Se precisar, sigo por aqui para qualquer assunto financeiro.",
        "pergunta_seguinte": "Posso ajudar com mais alguma coisa?",
        "encerrar": "",
    },
    {
        "tag": "saudacao",
        "prioridade": 19,
        "palavras": termos([
            "oi",
            "ola",
            "bom dia",
            "boa tarde",
            "boa noite",
            "tudo bem",
            "como vai",
            "eae",
            "salve",
            "fala",
            "hey",
            "hi",
            "hello",
            "oie",
            "ei",
            "opa",
            "alo",
            "e ai",
            "oioi",
            "oii",
            "oiii",
            "oiiii",
            "oiiiii",
            "oiiiiii",
            "boas",
            "posso perguntar",
            "pode me ajudar",
            "me ajuda",
            "preciso de ajuda",
            "socorro",
            "uai",
            "slv",
            "aloo",
            "opa tudo bem",
            "oopa",
            "ola financeiro",
            "bom dia financeiro",
            "boa tarde financeiro",
            "boa noite financeiro",
            "queria falar com o financeiro",
        ]),
        "resposta": (
            "Ola! Voce esta falando com o atendimento financeiro da FashionFlow. "
            "Posso ajudar com cobranca, pagamento, reembolso, nota fiscal, Pix ou cartao."
        ),
        "pergunta_seguinte": "",
        "encerrar": "",
    },
    {
        "tag": "atendimento_humano",
        "prioridade": 20,
        "palavras": termos([
            "atendente",
            "humano",
            "pessoa",
            "falar com alguem",
            "quero falar com atendente",
            "me passa pra um humano",
            "suporte humano",
            "atendimento humano",
            "nao quero falar com robo",
            "me transfere",
            "quero ser transferido",
            "quero ser transferida",
            "hmano",
            "presona",
            "algem",
            "supote",
            "trasfere",
            "falar com suporte",
            "chamar especialista",
            "me passa para uma pessoa de verdade",
            "atendente real",
            "quero falar com um ser humano",
        ]),
        "resposta": "Sem problemas. Vou te conectar com um atendente humano do Financeiro.",
        "pergunta_seguinte": "Deseja entrar na fila do atendimento humano agora? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "reclamacoes",
        "prioridade": 21,
        "palavras": termos([
            "nao gostei",
            "odiei",
            "pessimo",
            "ruim",
            "nota 0",
            "nota zero",
            "horrivel",
            "terrivel",
            "que droga",
            "ridiculo",
            "absurdo",
            "uma vergonha",
            "lamentavel",
            "decepcionante",
            "fui mal atendido",
            "fui mal atendida",
            "que raiva",
            "insatisfeito",
            "frustrado",
            "lixo",
            "frustado",
            "raiba",
            "pessimo sistema",
            "estou indignado",
            "estou indignada",
            "atendimento ruim",
            "sistema horrivel",
            "que absurdo",
            "vou reclamar",
        ]),
        "resposta": "Sinto muito pela experiencia. Vou tentar encaminhar isso do jeito certo.",
        "pergunta_seguinte": "Deseja falar com um atendente humano para resolvermos o caso? (s/n)",
        "encerrar": "",
    },
    {
        "tag": "duvidas_gerais",
        "prioridade": 30,
        "palavras": termos([
            "duvida",
            "pergunta",
            "tenho uma duvida",
            "queria perguntar",
            "queria tirar uma duvida",
            "to com duvida",
            "fiquei com duvida",
            "pode explicar",
            "me explica",
            "como funciona",
            "nao sei",
            "duvda",
            "djvida",
            "prgunta",
            "perguta",
            "nao intendi",
            "clmo funciona",
            "preciso tirar uma duvida",
            "me tira uma duvida",
            "uma pergunta rapida",
            "pode me esclarecer",
        ]),
        "resposta": (
            "Claro. Para eu te orientar melhor no Financeiro, diga se o assunto e "
            "cobranca, pagamento, reembolso, nota fiscal, Pix ou cartao."
        ),
        "pergunta_seguinte": "",
        "encerrar": "",
    },
]


with open("base_conhecimento.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
    writer.writeheader()
    writer.writerows(intencoes)

print(
    f"Arquivo base_conhecimento.csv gerado com {len(intencoes)} intencoes financeiras.")
